# Generated by Django 2.2.6 on 2019-10-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20191016_0309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infos_empresa',
            new_name='Informacoes',
        ),
        migrations.AlterModelTable(
            name='informacoes',
            table='informacoes',
        ),
    ]
