# Generated by Django 2.2.6 on 2019-12-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0003_auto_20191016_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quartos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='produto.Produto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrinho',
            },
        ),
    ]
