# Generated by Django 2.2.6 on 2019-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20191208_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quartos',
            field=models.IntegerField(default=0),
        ),
    ]
