# Generated by Django 2.2.6 on 2019-12-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20191208_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
